### ISSUE TITLE
[Improvement] PT-BR translation

### ISSUE THREAD

**Issue by Myiamoto86** [jason0611/FS22_DashboardLive#10]
Dear,

Goodnight.

First of all congratulations for the mod. Great.

I had the trouble to add the PT-BR translation to modDesc. I'm happy to provide it to you so you can feed it into an upcoming update.

hugs.
[modDesc.txt](https://github.com/jason0611/FS22_DashboardLive/files/10947121/modDesc.txt)

**Comment by jason0611** [comment]
I've added your translation into the dev version, so it will be included within the next update to ModHub.
Thank you very much.

**Comment by Myiamoto86** [comment]
Thank you. I hope to help with other projects.

Hugs.
