### ISSUE TITLE
Idea - work camera/back up cam

### ISSUE THREAD

**Issue by Rick2812g** [jason0611/FS22_DashboardLive#12]
I have an idea for a future update for DBL.

Maybe you could add work camera's that can be displayed in the cabin

**Comment by jason0611** [comment]
I'm not shure if this is possible. I've tried out a lot now, but found no way to integrate this into a terminal.

**Comment by Rick2812g** [comment]
maybe you can make it in the game HUD in the future.....    :)

**Comment by jason0611** [comment]
One goal of DBL is to support playing with the game's hud turned off. So a camera will be included only, if it's possible to integrate it into dashbords.
