### ISSUE TITLE
Frage

### ISSUE THREAD

**Issue by ppeell** [jason0611/FS22_DashboardLive#21]
Guten Tag zusammen ich habe da mal eine frage und zwar kann man sich ja unter Dashboard Live den Liter stand anzeigen lassen auf dem Display. Jetzt meine frage kann man sich auch die Prozent zahl anzeigen lassen zb. wie viel Prozent der Anhänger beladen ist und wenn ja wie?

Danke im Voraus

**Comment by jason0611** [comment]
Mit `option="abs"` wird die tatsächlich Füllmenge ausgegeben, genauso wie ohne `option`.
Mit `option="percent"`wird die Füllmenge in % ausgegeben, mit `option="max"` wird die maximal mögliche Füllmenge ermittelt.
In der Mod-Datei ist unter doc eine Anleitung als PDF-Datei enthalten. Darin ist die Befehlsübersicht verlinkt, die wir an zentraler Stelle pflegen und erweitern.
