### ISSUE TITLE
No filllevel Data

### ISSUE THREAD

**Issue by Enty2k** [jason0611/FS22_DashboardLive#38]
Hello, i dont know if im doing it wrong but i have just made my own display for a seeder that isent on the modhub or in the basegame. And i get everything to work except the filllevel data of the seeder so (filllevel for seeds and fertelizer.) Cuz when i connect a basegame seeder the filllevels display the seed and fertelizer amount on the display that i have made and installed in a tractor. 

It seems that the mod is missing something so it dosent get picked up by the valueType="base" cuz i have converted and made other seeders from 19 and those work do u know why it wont work?

**Comment by jason0611** [comment]
Hello,
it's a little bit difficulty to me to help without any further information like a vehicle's xml-file or similar.
The best way to solve your issue will be comparing the fillunit-section of your seeder with a fillunit-section of a basegame seeder.
Regards,
Martin

**Comment by jason0611** [comment]
Does the problem still exist or can we close this issue?
