### ISSUE TITLE
Bale counter and sizes

### ISSUE THREAD

**Issue by LazyEModding** [jason0611/FS22_DashboardLive#40]
Hello Jason,

First off, amazing mod. And this issue could be something that I am completely messing up. 

I am using the GitHub version to try and get the bale count to show on a bale monitor screen, along with the bale sizes if I can figure it out. 

I took the example that you had posted in GitHub, and added my nodes etc, it gives me a zero constantly, no matter if I am using the Vermeer DLC or the bale counter that you recommended (https://www.lsfarming-mods.com/filebase/file/69-ballenz%C3%A4hler/). Like I said, I could be messing something up so I am dropping the line of code in here, and attaching the XML I am working with aswell. 

Thank you!

`			<dashboard valueType="base"		cmd="fillLevel"		option="percent"	partition="1"	joints="1 2 3"		displayType="ANIMATION" 	animName="BALERFILLLEVEL"		groups="MOTOR_ACTIVE"	trailer="1"		minValueAnim="1"	maxValueAnim="100"	/>`

[series7R.zip](https://github.com/jason0611/FS22_DashboardLive/files/11854201/series7R.zip)

**Comment by HiPhi77** [comment]
to get the number of bales, use valueType baler with cmd baleCountAnz
e.g.
 <dashboard valueType="baler" 	cmd="baleCountAnz"	...

current balesize is given by the balesize command.

**Comment by LazyEModding** [comment]
> to get the number of bales, use valueType baler with cmd baleCountAnz e.g. <dashboard valueType="baler" cmd="baleCountAnz" ...
> 
> current balesize is given by the balesize command.

Awesome, thank you. I'll try that and see if I can get it to work, then close this issue.
