### ISSUE TITLE
How to add the DBL spec to a modded baler. 

### ISSUE THREAD

**Issue by LazyEModding** [jason0611/FS22_DashboardLive#42]
I am trying to get the info to display for a modded baler. It works with a base game baler just fine, but the modder baler it doesn't. The vehiclespec is set to baler, just not sure to to get it to work with DBL.

**Comment by jason0611** [comment]
Please share some more info with me: What baler makes the problems? Can you upload a logfile of your game, please?

**Comment by LazyEModding** [comment]
> Please share some more info with me: Which baler makes the problems? Can you upload a logfile of your game, please?

The baler is a John Deere 560M mod. I have attached the XML and ModDesc for the baler, along with the log of a save, and the XML for the tractor running DBL. XMLs are located in the zip file since GitHub doesn't support XML. 

[log.txt](https://github.com/jason0611/FS22_DashboardLive/files/11937419/log.txt)
[XMLs.zip](https://github.com/jason0611/FS22_DashboardLive/files/11937426/XMLs.zip)

**Comment by jason0611** [comment]
I had a look on your XML-Files:
The mod baler uses attacherJoint "trailerLow" (attacherJoint index 2), but you look at attacherJoints "1 3 4" for spec_baler.
I think this is the reason, why your mod baler doesn't show up correctly. You should try "1 2 3" instead.

**Comment by LazyEModding** [comment]
Okay, that makes sense now. Thank you!
