### ISSUE TITLE
Flackern des Bildschirmes bei...

### ISSUE THREAD

**Issue by LSMT-elMatador** [jason0611/FS22_DashboardLive#61]
... vorher eingebautem REAL GPS! 

In manchen Mod Traktoren wurden ja schon Billdschirme mit Real-GPS verbaut. Wenn jetzt der Dashboard-Live mod ab Version 1.3 im Ordner ist, flackert der vorher verbaute RealGPS!

**Comment by jason0611** [comment]
Leider kann ich das bei mir nicht reproduzieren. Mit welchen konkreten Fahrzeugen/Mods tritt das denn auf?
Ich habe es hier mit LSFM22_Fendt700Vario versucht, aber es flackert nichts.

**Comment by jason0611** [comment]
Hat sich das Thema erledigt?

**Comment by LSMT-elMatador** [comment]
Noch nicht wirklich, aber die Mod, die es schlimm betrifft, die ist Privat!
Aber der, den es stört, der hat einfach zurückgepacht und gut is!

**Comment by jason0611** [comment]
Ok, Danke für die Rückmeldung und ein frohes neues Jahr! :-)
