### ISSUE TITLE
fov control mod

### ISSUE THREAD

**Issue by wilsron** [jason0611/FS22_DashboardLive#62]
hey there is something wrong with the fov control mod it isnt bringing the menu up properly.

![20240113144031_1](https://github.com/jason0611/FS22_DashboardLive/assets/156526341/5edfec20-5b0b-4188-9408-adcd8cc659bd)

**Comment by jason0611** [comment]
Can you please be more specific? Do you have an issue with FS22_DashboardLive or are you talking about FS22_FovControl?

**Comment by wilsron** [comment]
> Can you please be more specific? Do you have an issue with FS22_DashboardLive or are you talking about FS22_FovControl?

its fs22_fovcontrol

**Comment by jason0611** [comment]
Then this is the wrong place, because I'm the author of DadhboardLive, while FovControl is made by VertexFloat.

**Comment by wilsron** [comment]
> Then this is the wrong place, because I'm the author of DadhboardLive, while FovControl is made by VertexFloat.

where do i need to get a hold of him

**Comment by jason0611** [comment]
I don't know. I think it would make sense, to try to reach him by the Giants Forum: https://forum.giants-software.com
