### ISSUE TITLE
Is it possible for "Quick Zoom" to only work in the cockpit?

### ISSUE THREAD

**Issue by vitalii2011** [jason0611/FS22_DashboardLive#73]
Now, when outside the vehicle, “Camera zoom in” does not work. 

https://github.com/jason0611/FS22_DashboardLive/assets/41552153/d5fa9aca-7012-4f56-9c77-2eb298dbd465

**Comment by vitalii2011** [comment]
"Quick Zoom":
![fsScreen_2024_04_13_11_31_27](https://github.com/jason0611/FS22_DashboardLive/assets/41552153/24c8ba6b-e1cd-41ca-afee-0593f244a1dd)
"Camera zoom in":
![fsScreen_2024_04_13_11_30_34](https://github.com/jason0611/FS22_DashboardLive/assets/41552153/3311311b-4378-4e23-8ca5-776a4a0ca859)

**Comment by vitalii2011** [comment]
"Quick Zoom":
![fsScreen_2024_04_13_11_31_27](https://github.com/jason0611/FS22_DashboardLive/assets/41552153/566c0a40-8158-42b2-86b6-537ee9e111a0)
"Camera zoom in":
![fsScreen_2024_04_13_11_30_34](https://github.com/jason0611/FS22_DashboardLive/assets/41552153/70b96b3a-6639-44d9-94b9-9ec1116772aa)

**Comment by jason0611** [comment]
The distance is handled by the game's engine, so I can't change it within DBL.
Maybe just try to use another keybinding?

**Comment by vitalii2011** [comment]
Of course I tried. But, on a gamepad it is difficult to find “unused”/convenient button combinations. 
All clear. 
Thanks for clarifying.
