### ISSUE TITLE
Keybinds issue

### ISSUE THREAD

**Issue by atledreier** [jason0611/FS22_DashboardLive#75]
I have a mod that supports DBL, and I can interact with it using interactive control, but keybinds (or buttons) aren't working. For instance, I can set day/night mode with IC, but the keybind for DBL does nothing.

Also I haven't seen any mods with any pages in the display, but I am not sure if those are implemented in the mods I have tried.

Are there any examples of mods that have pages of displays so I can test if this is working at all?

I have tried with ONLY this mod and a vehicle with DBL support active, and it's the same.

**Comment by jason0611** [comment]
The keybindings for page and group change are only active, if they are supported by the vehicle. Only the keybinding for zoom will be active always.
You can try out my Xerion, there you can switch to the upper terminal and switch between minimap and gps screen.
https://github.com/jason0611/FS22_Xerion_DBL
