### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MX5Marc** [jason0611/FS22_DashboardLive#79]
Hi,

I love the idea of being able subsc8be to a paid for dashboard or series of screens that are suitable for most vehicles. The screens placed in a terminal, and each time DBL is updated and added to, then the subscribed to dashboard updates and gets the new features. In order for it to be worth subscribing to, it would need to be fully featured.  Do you know if such a thing exists or is possible?

**Comment by jason0611** [comment]
I've not planned to create any paid-for-content.
You can use the CCI200-Terminal (https://www.farming-simulator.com/mod.php?mod_id=265138&title=fs2022) or use content from https://github.com/clanfreak1988/Dashboard-Live-Icon-Library.
