### ISSUE TITLE
Idea - Implementation of Combine XPerience

### ISSUE THREAD

**Issue by Mantikor83** [jason0611/FS22_DashboardLive#8]
Wäre großtartig, wenn Combine XPerience (https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=252266&title=fs2022) zur Liste der Unterstützten Mods aufgenommen werden würde. Das würde diesem tollen Script einen echten Anwendungsfall für Harvester geben.

Grüße

**Comment by jason0611** [comment]
Das ist bereits eingeplant. :-)
