### ISSUE TITLE
Fillwarning Sound einfügen.

### ISSUE THREAD

**Issue by xruinprincessx** [jason0611/FS22_DashboardLive#81]
Moin. Können Sie mir vielleicht helfen einen Warning sound für ein filllevel einzufügen? Ich habe in meinem Trecker eine Samson Bedienung mit Dbl und würde gerne wie beim original einen warning Sound einfügen der bei einem gewissen Level ertönt und am besten auch nur dann und nur beim güllefass. Ich müsste dann z.b eine Spanne eingeben und den loop so laufen lassen falls möglich das er genau dann stoppt wenn dieses niedrig Level erreicht ist. Als Beispiel 10%- 1% und das dies auch nur ertönt wenn die zapfwelle aktiv ist. Ich weiß nicht ob es möglich wäre diesen sound so laufen zu lassen, vielleicht kann man mir ja weiter helfen. Beste Grüße Heiko

**Comment by jason0611** [comment]
Moin,
im Xerion (ebenfalls hier im GitHub) habe ich eine entsprechende Funktion eingebaut, am besten schaust Du Dir das dort einmal an. Die Bedingungen "PTO" und "Güllefass" kann dann über entsprechende Gruppeneinträge ergänzt werden.

**Comment by xruinprincessx** [comment]
Moin,
Hast du vlt nen link zum Xerion? Würde mir sehr helfen. Besten Dank für die
Antwort, ich wünsche Ihnen noch einen schönen Tag.
Beste Grüße
Heiko

Glowins Modschmiede ***@***.***> schrieb am Mi., 24. Juli
2024, 13:28:

**Comment by xruinprincessx** [comment]
Moin hat sich erledigt. Bin neu hier, aber habe den xerion gefunden xD. Magst du mir vlt nen Eintrag schicken wie das dann aussehen muss wegen pto und güllefass? Würde mir mega helfen ich bin noch nicht so gut im XML umschreiben und könnte daher falls möglich hilfe gebrauchen. Beste Grüße Heiko

**Comment by jason0611** [comment]
Du musst unter `<groups>` folgende Gruppen anlegen:
```
<group name="MANUREBARREL" dbl="base_hasTypeDesc" dblOption="manureBarrel" attacherJointIndices="1 2 3 5"/>
<group name="DBL_PTO_ACTIVE" op="and" dbl="base_pto" dblAttacherJoints="1 2 3 5" />
```

Dann kannst Du diese beiden Gruppen den XML-Zeilen für den Füllstand hinzufügen, damit sie nur aktiv sind, wenn ein Güllefass angehängt ist und die PTO aktiv ist.

**Comment by xruinprincessx** [comment]
Moin mein lieber kannst du mir vlt bei dem problem helfen? ich weiß nicht
wie ich die lines kombinieren kann das es funktioniert. das hier ist
bestand: <dashboardgroup name="MANUREBARREL" cmd="fillLevel" joints="3"
option="percent" displayType="AUDIO" audioName="FillLevelBar_Liquid"
loop="4" volume="1.5" audioFile="sounds/Fillwarning Samson.ogg" cond="less"
factor="100" condValue="10" groups="ManureBarrel" /> hab ich grob mal
zusammen gefummelt vlt weißt du ja was ich verkackt habe.
beste grüße heiko


Am Mo., 26. Aug. 2024 um 22:41 Uhr schrieb Glowins Modschmiede <
***@***.***>:
