### ISSUE TITLE
Dashboard Live on Apple Silicon (Mac M1)

### ISSUE THREAD

**Issue by haritos90** [jason0611/FS22_DashboardLive#84]
Hello!

I am playing FS22 on a Mac. The game and most mods work perfectly (I use about 20-30 mods), and I only have problems with 2 - Interactive Controls and Dashboard Live.
As far as I understand, Dashboard Live requires no separate installation steps, you just download it and it works with compatible vehicles. This is just not the case for me. I tried it with Challenger MT700, John Deere 7R 270, Faresin Leader PF 2.26 Plus (TMR mixer). The screens remain as default and key bindings for screen rotation don't show up.
However, the Zoom option that this mod provides works perfectly and I use it a lot. I would still want the rest of the mods to work correctly.
Is there something I am doing wrong, or is this mod just not compatible with Apple Silicon Macs?

Many thanks in advance!

**Comment by jason0611** [comment]
Hi, like InteractiveControl DashboardLive (DBL) has to be build into the vehicles first. So most in-game vehicles are without DBL, only the Fendt 700 Series tractors have DBL Terminals inserted and the MAN has got a MiniMap on it's central display. 
For full DBL integration you have to look for mods with DBL at ModHub or at other community places like Forbidden Mods or several Discord Servers. 
Greetings, 
Martin

**Comment by jason0611** [comment]
By the way, both mods work very fine on Mac. I'm developing on Mac (Intel and Silicon). ;-)

**Comment by haritos90** [comment]
Thank you so much! Works like a charm now! I though that the description about supported vehicles only applied to the modded ones, and the base game vehicles are already included. Now I see this mod provides a framework other mod creators work with.
Thanks again!
